python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/02 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/03 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/04 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/05 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/06 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/07 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/08 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/09 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/10 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/11 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/12 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/13 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/14 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/15 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/16 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/17 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/18 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/19 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/20 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/21 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/22 --save_result image
python tools/demo_custom_kw.py -f exps/example/mot/yolox_x_custom_kw.py -c pretrained/bytetrack_x_mot17.pth.tar --path datasets/crosswalk_dataset/gopro/WITH_CROSSWALK/23 --save_result image